#!/bin/bash
#PBS -N NACA_GUST
#PBS -q cpu
#PBS -l select=1:ncpus=16:mpiprocs=16
#PBS -l walltime=24:00:00
#PBS -j oe

cd /work/u10677113/NACA2312

source /software/spack/share/spack/setup-env.sh
source /work/u10677113/NACA2312/my_venv/bin/activate

cd cosim_main
python3 cosim_driver.py --np 16 --window 50 --t-end 0.5 \
    --from-checkpoint \
    --gust-w0 0.0 --gust-t-start 0.0 --gust-t-end 0.8 \
    2>&1 | tee log.cosim_gust
